In [1]:
import numpy as np
import sys
import os
import neuro
import risp
import random

from encode import Chromagram
from encode import Encoder
from data_loader import DataLoader
import risp
import neuro
import eons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

In [2]:
risp_config = {
  "leak_mode": "all",
  "min_weight": -1,
  "max_weight": 1,
  "min_threshold": -1,
  "max_threshold": 1,
  "max_delay": 5,
  "discrete": False
} 
proc = risp.Processor(risp_config) # RISP processor

net = neuro.Network() # Neuro network
net.set_properties(proc.get_network_properties()) # Set network properties

n_inputs = 12
n_hidden = 360
n_outputs = 10
n_neurons = n_inputs + n_hidden + n_outputs
n_synapses = 1000


moa = neuro.MOA()
moa.seed(42)


In [3]:
def create_neuron(neuron_id, net, moa):
    neuron = net.add_node(neuron_id)
    net.randomize_node_properties(moa, neuron)
    return neuron

for i in range(n_inputs):
    neuron = create_neuron(i, net, moa)
    neuron.set("Threshold",0.75)
    net.add_input(i)
    
for i in range(n_outputs):
    neuron = create_neuron(i+n_inputs, net, moa)
    neuron.set("Threshold",0.75)
    net.add_output(i)
    
for i in range(n_hidden):
    neuron = create_neuron(i+n_inputs+n_outputs, net, moa)

In [4]:
# First, split the data into training+validation and testing sets
X_temp, X_test, y_temp, y_test = train_test_split(DataLoader().chroma_files, DataLoader().numerical_label_roots, test_size=0.2, random_state=42)

# Now, split the training+validation set into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.25, random_state=42)  # 0.25 x 0.8 = 0.2

# One-hot encode the labels
OneHot = OneHotEncoder(sparse_output=False)
y_train_encoded = OneHot.fit_transform(np.array(y_train).reshape(-1, 1))
y_val_encoded = OneHot.transform(np.array(y_val).reshape(-1, 1))
y_test_encoded = OneHot.transform(np.array(y_test).reshape(-1, 1))

In [5]:
print(DataLoader().numerical_label_roots)

[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 7, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 7, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 7, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 7, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 3, 

In [58]:
len(X_train)

1752

In [59]:
y_train_encoded[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [59]:
loader_instance = DataLoader(folders= ["minor_triad", "major_triad" ])

In [60]:
X_temp3, X_test3, y_temp3, y_test3 = train_test_split(loader_instance.chroma_files, loader_instance.numerical_label_types, test_size=0.2, random_state=42)

X_train3, X_val3, y_train3, y_val3 = train_test_split(X_temp3, y_temp3, test_size=0.25, random_state=42)  # 0.25 x 0.8 = 0.2


TwoeHot = OneHotEncoder(sparse_output=False)
y_train3_encoded = OneHot.fit_transform(np.array(y_train3).reshape(-1, 1))
y_val3_encoded = OneHot.transform(np.array(y_val3).reshape(-1, 1))
y_test3_encoded = OneHot.transform(np.array(y_test3).reshape(-1, 1))

In [61]:
y_test3[0]

1

In [62]:
encoder = Encoder(X_test3[2])

len(encoder.spikes)

6933

In [63]:
proc.load_network(net)

True

In [64]:
for i in range(n_outputs):
    proc.track_output_events(i)
    print(proc.track_output_events(i))

True
True
True
True
True
True
True
True
True
True


In [65]:
proc.apply_spikes(encoder.spikes)

In [66]:
proc.run(encoder.time_steps * encoder.num_frames * 4)

In [67]:
predicted_index = proc.output_count_max(n_outputs)[0]
one_hot_prediction = np.zeros(n_outputs)
one_hot_prediction[predicted_index] = 1.0

In [68]:
print("Shape of y_predict:", np.shape(one_hot_prediction))
print("Shape of y_test:", np.shape(y_test3_encoded[0]))

Shape of y_predict: (10,)
Shape of y_test: (2,)


In [69]:
len(OneHot.categories_[0])

2

In [34]:
proc.output_counts()

[875, 760, 467, 803, 791, 481, 381, 497, 435, 480]

In [48]:
output_count = np.array(proc.output_counts())
predicted_index = np.argmax(output_count)
print(predicted_index)

0


In [49]:
one_hot_prediction = np.zeros(n_outputs)
one_hot_prediction

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
one_hot_prediction[predicted_index]=1

In [51]:
one_hot_prediction

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
orginal_note = loader_instance.get_original_labels(one_hot_prediction.reshape(1, -1))
orginal_note

['A']

In [33]:
X_train[2]

'/home/dofo/Repos/Github/neuromorphicsnn/chord_snn/dataset/npy_chroma_chords/dom7_seventh/MODX8_dom7seventh_G#4_68.npy'

In [35]:
y_train[2]

11

In [20]:
# * 5 -> 1142

# * 6 -> 1378

# * 7 -> 1610

# * 8 -> 1676

In [71]:
import json
import argparse


In [77]:
def load_json_arg(str_or_fn):
    if (str_or_fn == None):
        return {}
    elif (str_or_fn[0] == "{"):
        params = json.loads(str_or_fn)
    else:
        with open(str_or_fn) as f:
            params = json.loads(f.read())
            f.close()
    return params

eo_params = load_json_arg('/home/dofo/Repos/Github/neuromorphicsnn/chord_snn/config/eons.json')

In [78]:
eo_params

{'starting_nodes': 60,
 'starting_edges': 60,
 'merge_rate': 0,
 'population_size': 50,
 'multi_edges': 0,
 'crossover_rate': 0.5,
 'mutation_rate': 0.9,
 'selection_type': 'tournament',
 'tournament_size_factor': 0.3,
 'tournament_best_net_factor': 0.9,
 'random_factor': 0,
 'num_mutations': 5,
 'node_mutations': {'Threshold': 1.0},
 'net_mutations': {},
 'edge_mutations': {'Weight': 0.7, 'Delay': 0.3},
 'num_best': 2,
 'add_node_rate': 0.25,
 'delete_node_rate': 0.75,
 'add_edge_rate': 0.25,
 'delete_edge_rate': 0.75,
 'node_params_rate': 2.5,
 'edge_params_rate': 2.5,
 'net_params_rate': 0}

In [79]:
evolver = eons.EONS(eo_params)